CREATE DATABASE /*!32312 IF NOT EXISTS*/`duralex` /*!40100 DEFAULT CHARACTER SET utf8 */;
/*ACTUALIZACION */
USE `duralex`;


CREATE TABLE ROLES(
ID INT PRIMARY KEY NOT NULL,
DESCRIPCION VARCHAR(100)
);

insert into ROLES (ID, DESCRIPCION) values (0 , 'Sin Perfil');
insert into ROLES (ID, DESCRIPCION) values (1 , 'Gerente');
insert into ROLES (ID, DESCRIPCION) values (2 , 'Administrador');
insert into ROLES (ID, DESCRIPCION) values (3 , 'Secretaria');
insert into ROLES (ID, DESCRIPCION) values (4 , 'Cliente');



CREATE TABLE USUARIO(
 ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT
,RUT VARCHAR(100) NOT NULL
,NOMBRE VARCHAR(100) NOT NULL
,FECHA VARCHAR(100) DEFAULT NULL
,TIPO_PERSONA VARCHAR(100) NOT NULL
,DIRECCION VARCHAR(100) NOT NULL
,CELULAR VARCHAR(100) NOT NULL
,CONTRASENA VARCHAR(100) NOT NULL
,ID_PADRE VARCHAR(100)
);


insert into USUARIO (ID, RUT, NOMBRE, FECHA, TIPO_PERSONA, DIRECCION, CELULAR,CONTRASENA,ID_PADRE) VALUES (1,'1-9','Hugo','27-06-2017','Natural','personal@rescue.cl','9999999','1234',null);
insert into USUARIO (ID, RUT, NOMBRE, FECHA, TIPO_PERSONA, DIRECCION, CELULAR,CONTRASENA,ID_PADRE) VALUES (2,'2-9','Pedro','27-06-2017','Natural','padre@rescue.cl','9999999','1234',null);
insert into USUARIO (ID, RUT, NOMBRE, FECHA, TIPO_PERSONA, DIRECCION, CELULAR,CONTRASENA,ID_PADRE) VALUES (3,'3-9','Hijo','27-06-2017','Juridica','hijo@rescue.cl','9999999','1234',2);

